name: Node.js CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                go-version:
                    - '1.23'
                    - '1.24'
                    - '1.25'

        steps:
        - uses: actions/checkout@v5
        - uses: actions/setup-go@v5
        - name: Test
          run: go test -v -race ./...
