name: CI Test

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                go-version:
                    - '1.23'
                    - '1.24'
                    - '1.25'

        steps:
        - uses: actions/checkout@v5
        - uses: actions/setup-go@v5
        - name: Unit Tests
          run: go test -v -race ./...
        - name: Acceptance Tests
          run: |
            mkdir -p ./_data
            go run ./example/example-server > ./_data/server.log 2>&1 &
            timeout 30s go run ./example/example-client | tee ./_data/client.log
        - name: Upload debug artifacts on failure
          if: failure()
          uses: actions/upload-artifact@v4
          with:
            name: debug-data-${{ matrix.go-version }}-${{ github.run_number }}
            path: _data/
            retention-days: 7
